version: '3.8'

services:
  app:
    build:
      context: .
    container_name: smart_tracker_app
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PYTHONPATH=/app
      - DATABASE_HOST=db
      - DATABASE_PORT=5433
      - POSTGRES_DB=tracker_db_recent
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres@123
    command: >
      sh -c "./wait-for-db.sh python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8081"
    depends_on:
      - db
    ports:
      - "8081:8081"
  db:
    image: postgres:15
    container_name: smart_tracker_db
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres@123
      POSTGRES_DB: tracker_db_recent
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped  # Restart unless explicitly stopped

volumes:
  db_data:
